spin_version = "1"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""
name = "http-rust-example"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "http-rust-example"
source = "target/wasm32-wasi/release/http_rust_example.wasm"
allowed_http_hosts = []
key_value_stores = ["default"]
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
